### PR TITLE
Add LICENSE file

### PR DESCRIPTION
**Pull request by fabaff**

### CODE REVIEW

**Comment by fabaff** [comment]
Could you merge this please? Then I'm able to ship the license as part of the Fedora RPM package. Thanks.

**Comment by fabaff** [comment]
@skelsec, could you please merge this is?

**Comment by skelsec** [comment]
@fabaff I definitely can't merge this. Reason: I have no idea what the correct license for this code is, but it's definitely not MIT as it contains code from [Impacket](https://github.com/SecureAuthCorp/impacket)

**Comment by fabaff** [comment]
The [`setup.py` file](https://github.com/skelsec/aiosmb/blob/master/setup.py#L53) says MIT. `impacket` is licensed under ASL and ASL is a permissive license. As far as I know, can modified or derived code be under a different license. Unmodified code needs to stay under ASL.

**Comment by skelsec** [comment]
The setup.py is incorrect in that case. (probably a leftover from copypaste, sorry. I'll fix it in the next update)  
As for the MIT license part: I don't think that it will cut it in this case because I haven't seen any articles stating that's it's okay to "downgrade" the license. The only option I see is either an apache license or "updating" it to GPLv3 / LGPL.  But again, I'm not a lawyer and absolutely not versed in the licensing topic. I have asked around already abt this but all I'm getting is contradicting info :/

**Comment by noraj** [comment]
no license = COPYRIGHTED, so in theory other project don't have the right to ship it, and linux distro don't have the rights to embed it, so please choose an OSI license for all your projects

**Pull request closed without merging**
